

IF DB_ID('RealEstate') IS NULL
BEGIN
    CREATE DATABASE RealEstate;
END
GO

USE RealEstate;
GO



IF OBJECT_ID('FK_IS_FOR_PROPERTY', 'F') IS NOT NULL
ALTER TABLE IS_FOR DROP CONSTRAINT FK_IS_FOR_PROPERTY;
GO

IF OBJECT_ID('FK_IS_FOR_CLIENT', 'F') IS NOT NULL
ALTER TABLE IS_FOR DROP CONSTRAINT FK_IS_FOR_CLIENT;
GO

IF OBJECT_ID('FK_PROPERTY_VIEW_CLIENT', 'F') IS NOT NULL
ALTER TABLE PROPERTY_VIEW DROP CONSTRAINT FK_PROPERTY_VIEW_CLIENT;
GO

IF OBJECT_ID('FK_PROPERTY_VIEW_PROPERTY', 'F') IS NOT NULL
ALTER TABLE PROPERTY_VIEW DROP CONSTRAINT FK_PROPERTY_VIEW_PROPERTY;
GO

IF OBJECT_ID('FK_PROPERTY_REPRESENTATIVE', 'F') IS NOT NULL
ALTER TABLE PROPERTY DROP CONSTRAINT FK_PROPERTY_REPRESENTATIVE;
GO



IF OBJECT_ID('TRANSACTIONS', 'U') IS NOT NULL
DROP TABLE TRANSACTIONS;
GO

IF OBJECT_ID('TOUR', 'U') IS NOT NULL
DROP TABLE TOUR;
GO

IF OBJECT_ID('AGREEMENT', 'U') IS NOT NULL
DROP TABLE AGREEMENT;
GO

IF OBJECT_ID('PROPERTY_VIEW', 'U') IS NOT NULL
DROP TABLE PROPERTY_VIEW;
GO

IF OBJECT_ID('IS_FOR', 'U') IS NOT NULL
DROP TABLE IS_FOR;
GO

IF OBJECT_ID('PROPERTY', 'U') IS NOT NULL
DROP TABLE PROPERTY;
GO

IF OBJECT_ID('CLIENT', 'U') IS NOT NULL
DROP TABLE CLIENT;
GO

IF OBJECT_ID('REPRESENTATIVE', 'U') IS NOT NULL
DROP TABLE REPRESENTATIVE;
GO



CREATE TABLE REPRESENTATIVE (
    REPRESENTATIVE_ID INT IDENTITY(1,1) ,
    FULL_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    LICENSE_NUMBER VARCHAR(50),

    CONSTRAINT PK_REPRESENTATIVE PRIMARY KEY (REPRESENTATIVE_ID)
);
GO



CREATE TABLE CLIENT (
    CLIENT_ID INT IDENTITY(1,1),
    FULL_NAME VARCHAR(100) NOT NULL,
    CLIENT_CONTACT_PREFERENCE VARCHAR(100),
    CLIENT_PHONE VARCHAR(20),
    CLIENT_EMAIL VARCHAR(100),

    CONSTRAINT PK_CLIENT PRIMARY KEY (CLIENT_ID)
);
GO


CREATE TABLE PROPERTY (
    PROPERTY_ID INT IDENTITY(1,1),
    REPRESENTATIVE_ID INT,
    STYLE VARCHAR(100) NOT NULL,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    MARKET_VALUE DECIMAL(12,2) NOT NULL,
    PROPERTY_STATUS VARCHAR(100),

    CONSTRAINT PK_PROPERTY PRIMARY KEY (PROPERTY_ID)
);
GO



CREATE TABLE TOUR (
    TOUR_ID INT IDENTITY(1,1) NOT NULL,
    CLIENT_ID INT,
    PROPERTY_ID INT,
    REPRESENTATIVE_ID INT,
    TOUR_DATE DATE,
    TOUR_TIME TIME,

    CONSTRAINT PK_TOUR PRIMARY KEY (TOUR_ID)
);
GO


CREATE TABLE AGREEMENT (
    AGREE_ID INT IDENTITY(1,1) NOT NULL,
    CLIENT_ID INT,
    PROPERTY_ID INT,
    FINAL_PRICE DECIMAL(12,2),
    EFFECTIVE_DATE DATE,

    CONSTRAINT PK_AGREEMENT PRIMARY KEY (AGREE_ID)
);
GO


CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT IDENTITY(1,1) NOT NULL,
    CLIENT_ID INT,
    TOUR_ID INT,
    REPRESENTATIVE_ID INT,
    TRANSACTION_AMOUNT DECIMAL(12,2),
    TRANSACTION_STATUS VARCHAR(20),
    TRANSACTION_DATE DATETIME,

    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID)
);
GO



CREATE TABLE IS_FOR (
    CLIENT_ID INT NOT NULL,
    TOUR_ID INT NOT NULL,
    PROPERTY_ID INT NOT NULL,

    CONSTRAINT PK_IS_FOR PRIMARY KEY (CLIENT_ID, TOUR_ID, PROPERTY_ID)
);
GO



CREATE TABLE PROPERTY_VIEW (
    CLIENT_ID INT NOT NULL,
    PROPERTY_ID INT NOT NULL,

    CONSTRAINT PK_PROPERTY_VIEW PRIMARY KEY (CLIENT_ID, PROPERTY_ID)
);
GO



CREATE NONCLUSTERED INDEX IDX_IS_FOR_PROPERTY
ON IS_FOR (PROPERTY_ID ASC);
GO

CREATE NONCLUSTERED INDEX IDX_PROPERTY_VIEW_CLIENT
ON PROPERTY_VIEW (CLIENT_ID ASC);
GO

CREATE NONCLUSTERED INDEX IDX_PROPERTY_VIEW_PROPERTY
ON PROPERTY_VIEW (PROPERTY_ID ASC);
GO



ALTER TABLE PROPERTY
ADD CONSTRAINT FK_PROPERTY_REPRESENTATIVE
FOREIGN KEY (REPRESENTATIVE_ID)
REFERENCES REPRESENTATIVE (REPRESENTATIVE_ID);
GO

ALTER TABLE TOUR
ADD CONSTRAINT FK_TOUR_CLIENT
FOREIGN KEY (CLIENT_ID)
REFERENCES CLIENT (CLIENT_ID);
GO

ALTER TABLE TOUR
ADD CONSTRAINT FK_TOUR_PROPERTY
FOREIGN KEY (PROPERTY_ID)
REFERENCES PROPERTY (PROPERTY_ID);
GO

ALTER TABLE TOUR
ADD CONSTRAINT FK_TOUR_REPRESENTATIVE
FOREIGN KEY (REPRESENTATIVE_ID)
REFERENCES REPRESENTATIVE (REPRESENTATIVE_ID);
GO

ALTER TABLE AGREEMENT
ADD CONSTRAINT FK_AGREEMENT_CLIENT
FOREIGN KEY (CLIENT_ID)
REFERENCES CLIENT (CLIENT_ID);
GO

ALTER TABLE AGREEMENT
ADD CONSTRAINT FK_AGREEMENT_PROPERTY
FOREIGN KEY (PROPERTY_ID)
REFERENCES PROPERTY (PROPERTY_ID);
GO

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_TRANSACTIONS_CLIENT
FOREIGN KEY (CLIENT_ID)
REFERENCES CLIENT (CLIENT_ID);
GO

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_TRANSACTIONS_TOUR
FOREIGN KEY (TOUR_ID)
REFERENCES TOUR (TOUR_ID);
GO

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_TRANSACTIONS_REPRESENTATIVE
FOREIGN KEY (REPRESENTATIVE_ID)
REFERENCES REPRESENTATIVE (REPRESENTATIVE_ID);
GO

ALTER TABLE IS_FOR
ADD CONSTRAINT FK_IS_FOR_CLIENT
FOREIGN KEY (CLIENT_ID)
REFERENCES CLIENT (CLIENT_ID);
GO

ALTER TABLE IS_FOR
ADD CONSTRAINT FK_IS_FOR_PROPERTY
FOREIGN KEY (PROPERTY_ID)
REFERENCES PROPERTY (PROPERTY_ID);
GO

ALTER TABLE PROPERTY_VIEW
ADD CONSTRAINT FK_PROPERTY_VIEW_CLIENT
FOREIGN KEY (CLIENT_ID)
REFERENCES CLIENT (CLIENT_ID);
GO

ALTER TABLE PROPERTY_VIEW
ADD CONSTRAINT FK_PROPERTY_VIEW_PROPERTY
FOREIGN KEY (PROPERTY_ID)
REFERENCES PROPERTY (PROPERTY_ID);
GO



INSERT INTO REPRESENTATIVE (FULL_NAME, PHONE, EMAIL, LICENSE_NUMBER) VALUES
( 'Ahmed Hassan', '01011111111', 'ahmed@realestate.com', 'LIC1001'),
( 'Sara Ali', '01022222222', 'sara@realestate.com', 'LIC1002'),
( 'Omar Khaled', '01033333333', 'omar@realestate.com', 'LIC1003');
GO



INSERT INTO CLIENT (FULL_NAME, CLIENT_CONTACT_PREFERENCE, CLIENT_PHONE, CLIENT_EMAIL)
VALUES
( 'Mohamed Adel', 'Phone', '01111111111', 'mohamed@gmail.com'),
( 'Nour Tarek', 'Email', '01222222222', 'nour@gmail.com'),
( 'Youssef Samy', 'Phone', '01333333333', 'youssef@gmail.com'),
('Mariam Ali', 'Email', '01444444444', 'mariam@gmail.com'),
('Khaled Mostafa', 'Phone', '01555555555', 'khaled@gmail.com');
GO



INSERT INTO PROPERTY (REPRESENTATIVE_ID, STYLE, LATITUDE, LONGITUDE, ADDRESS, MARKET_VALUE, PROPERTY_STATUS)
VALUES
(1,'Villa',30.0444,31.2357,'Nasr City, Cairo',5500000,'Available'),
(1,'Apartment',30.0500,31.2400,'Heliopolis, Cairo',2500000,'Sold'),
(2,'Duplex',29.9765,31.1313,'6th October',4300000,'Available'),
(2,'Studio',30.0131,31.2089,'Maadi, Cairo',1800000,'Available'),
(3,'Villa',31.2001,29.9187,'Alexandria',6200000,'Sold'),
(3,'Apartment',30.1000,31.3000,'New Cairo',3200000,'Available');
GO



INSERT INTO TOUR INSERT INTO TOUR (CLIENT_ID, PROPERTY_ID, REPRESENTATIVE_ID, TOUR_DATE, TOUR_TIME)
VALUES
( 1, 1, 1, '2026-04-05', '10:00'),
( 2, 1, 1, '2026-04-10', '12:00'),
( 3, 2, 1, '2026-04-12', '14:00'),
( 1, 3, 2, '2026-04-15', '11:00'),
( 4, 3, 2, '2026-04-18', '13:00'),
( 5, 5, 3, '2026-04-20', '15:00'),
( 2, 5, 3, '2026-04-25', '09:00');
GO



INSERT INTO AGREEMENT
(CLIENT_ID, PROPERTY_ID, FINAL_PRICE, EFFECTIVE_DATE)
 VALUES
(2, 2, 2450000, '2026-04-28'),
(5, 5, 6100000, '2026-04-30');
GO



INSERT INTO TRANSACTIONS
(CLIENT_ID, TOUR_ID, REPRESENTATIVE_ID, TRANSACTION_AMOUNT, TRANSACTION_STATUS, TRANSACTION_DATE)
VALUES
( 2, 3, 1, 2450000, 'Completed', '2026-04-28'),
( 5, 6, 3, 6100000, 'Completed', '2026-04-30'),
( 1, 1, 1, 0, 'Pending', '2026-04-05');
GO



INSERT INTO PROPERTY_VIEW VALUES
(1,1),
(2,1),
(3,1),
(4,3),
(5,5),
(2,5),
(1,3),
(3,2);
GO



INSERT INTO IS_FOR VALUES
(1,1,1),
(2,2,1),
(3,3,2),
(1,4,3),
(4,5,3),
(5,6,5),
(2,7,5);
GO


SELECT TOP 1
    P.STYLE,
    COUNT(DISTINCT PV.CLIENT_ID) AS TOTAL_VIEWS,
    COUNT(DISTINCT T.TOUR_ID) AS TOTAL_TOURS
FROM PROPERTY P
LEFT JOIN PROPERTY_VIEW PV
    ON P.PROPERTY_ID = PV.PROPERTY_ID
LEFT JOIN TOUR T
    ON P.PROPERTY_ID = T.PROPERTY_ID
GROUP BY P.STYLE
ORDER BY TOTAL_TOURS DESC, TOTAL_VIEWS DESC;
GO

SELECT
    P.PROPERTY_ID,
    P.ADDRESS,
    P.STYLE
FROM PROPERTY P
WHERE P.PROPERTY_ID NOT IN (
    SELECT PROPERTY_ID
    FROM TOUR
    WHERE MONTH(TOUR_DATE) = MONTH(GETDATE()) - 1
);
GO



SELECT TOP 1
    R.FULL_NAME,
    SUM(T.TRANSACTION_AMOUNT) AS TOTAL_SALES
FROM TRANSACTIONS T
JOIN REPRESENTATIVE R
    ON T.REPRESENTATIVE_ID = R.REPRESENTATIVE_ID
WHERE T.TRANSACTION_STATUS = 'Completed'
AND MONTH(T.TRANSACTION_DATE) = MONTH(GETDATE()) - 1
GROUP BY R.FULL_NAME
ORDER BY TOTAL_SALES DESC;
GO



SELECT
    C.CLIENT_ID,
    C.FULL_NAME,
    C.CLIENT_EMAIL
FROM CLIENT C
WHERE C.CLIENT_ID NOT IN (
    SELECT CLIENT_ID
    FROM TOUR
    WHERE MONTH(TOUR_DATE) = MONTH(GETDATE()) - 1
);
GO



SELECT
    R.FULL_NAME AS REPRESENTATIVE_NAME,
    P.PROPERTY_ID,
    P.ADDRESS,
    P.STYLE,
    P.MARKET_VALUE
FROM PROPERTY P
JOIN REPRESENTATIVE R
    ON P.REPRESENTATIVE_ID = R.REPRESENTATIVE_ID
WHERE P.PROPERTY_STATUS = 'Available'
ORDER BY R.FULL_NAME;
GO



SELECT
    C.FULL_NAME,
    C.CLIENT_PHONE,
    C.CLIENT_EMAIL,
    COUNT(T.TOUR_ID) AS TOTAL_TOURS
FROM CLIENT C
LEFT JOIN TOUR T
    ON C.CLIENT_ID = T.CLIENT_ID
GROUP BY
    C.FULL_NAME,
    C.CLIENT_PHONE,
    C.CLIENT_EMAIL;
GO
